CREATE TABLE `_TABLE_NAME_` (
    `date` DATE NOT NULL,
    `time` TIME NOT NULL,
    `datetimems` BIGINT(12) NOT NULL,
    `version` TINYINT(4) NOT NULL,
    `srvstartts` BIGINT(12) NOT NULL,
    `requestid` INT(11) NOT NULL,
    `requeststatus` VARCHAR(16) NOT NULL,
    `cpreason` VARCHAR(16) NOT NULL,
    `threadid` VARCHAR(32) NOT NULL,
    `clientip` VARCHAR(15) NOT NULL,
    `requestmethod` VARCHAR(8) NOT NULL,
    `requesturl` TEXT,
    `executiontimems` BIGINT(12) NOT NULL,
    `usedmemorypct` INT(11) NOT NULL,
    `maxmemorykb` INT(11) NOT NULL,
    `usedmemorykb` INT(11) NOT NULL,
    `totalmemorykb` INT(11) NOT NULL,
    `freememorykb` INT(11) NOT NULL,
    `querystring` TEXT,
    `returnstatuscode` TINYINT(4) NOT NULL,
    `cputimems` BIGINT(12) NOT NULL,
    `amfrequest`TEXT,
    `jsessionid` TEXT,
    `cfid` TEXT,
    `cftoken` TEXT,
    `jdbcquerycount` INT(11) NOT NULL,
    `jdbctotaltimems` BIGINT(12) NOT NULL,
    `jdbctotaldbtimems` BIGINT(12) NOT NULL,
    `jdbctotalrows` INT(11) NOT NULL,
    `bytessent` INT(11) NOT NULL,
    `ttfirstbytems` BIGINT(12) NOT NULL,
    `ttlastbytems` BIGINT(12) NOT NULL,
    `ttstreamopenms` BIGINT(12) NOT NULL,
    `ttstreamclosems` BIGINT(12) NOT NULL,
    `useragentstring` TEXT
);